/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:55
-- pg_snowid::gen_snowid
CREATE  FUNCTION "gen_snowid"(
	"table_name" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'gen_snowid_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:48
-- pg_snowid::get_node_id
CREATE  FUNCTION "get_node_id"() RETURNS smallint /* i16 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_node_id_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:62
-- pg_snowid::get_snowid_timestamp
CREATE  FUNCTION "get_snowid_timestamp"(
	"id" bigint, /* i64 */
	"table_name" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_snowid_timestamp_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:39
-- pg_snowid::set_node_id
CREATE  FUNCTION "set_node_id"(
	"node" smallint /* i16 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_node_id_wrapper';
/* </end connected objects> */

